### ISSUE TITLE
C++ extension problem

### ISSUE THREAD

**Issue by muzi-Lu** [XinWu98/SC-wLS#3]
Hello，This is a excellent work!
When I compile the C++ code of DSAC*,it came to FAILED: /home/BB/code/SC-wLS/dsacstar/build/temp.linux-x86_64-cpython-38/dsacstar.o And cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++.
Finally,it came to RuntimeError: Error compiling objects for extension.
I wander what happened in this code and how to solve it?
Thanks

**Comment by XinWu98** [comment]
Hi, thanks for your attention! 
According to the reported error message you said in issue 1, it seems the opencv you used is not the right version. Make sure you follow the install steps in [DSAC*](https://github.com/vislearn/dsacstar#installation), and use `opencv (3.4.15)` instead. 
You could change the opencv path in `setup.py` file to make sure it use the right version.

**Comment by muzi-Lu** [comment]
谢谢您的回复，我关闭一下这个问题。
